// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBfKKUrBg24lBd09LtiGUHNdx5VwyR1tA',
    appId: '1:1001323050616:web:1865c209a2561fd96c5f8d',
    messagingSenderId: '1001323050616',
    projectId: 'airplanenurf',
    authDomain: 'airplanenurf.firebaseapp.com',
    storageBucket: 'airplanenurf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBziSkmHOj51yNZYbp-Dj1i-G3tE7-ZH04',
    appId: '1:1001323050616:android:2d6ec697730aeab66c5f8d',
    messagingSenderId: '1001323050616',
    projectId: 'airplanenurf',
    storageBucket: 'airplanenurf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh_Q6wj_4mjy7LMe3ubc2Boraj-gcc87M',
    appId: '1:1001323050616:ios:08df856b4d3d4d536c5f8d',
    messagingSenderId: '1001323050616',
    projectId: 'airplanenurf',
    storageBucket: 'airplanenurf.firebasestorage.app',
    iosBundleId: 'com.nurf.airPlane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh_Q6wj_4mjy7LMe3ubc2Boraj-gcc87M',
    appId: '1:1001323050616:ios:3d5e3fc01e9377cc6c5f8d',
    messagingSenderId: '1001323050616',
    projectId: 'airplanenurf',
    storageBucket: 'airplanenurf.firebasestorage.app',
    iosBundleId: 'com.example.airPlane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBfKKUrBg24lBd09LtiGUHNdx5VwyR1tA',
    appId: '1:1001323050616:web:4f716c159a143b506c5f8d',
    messagingSenderId: '1001323050616',
    projectId: 'airplanenurf',
    authDomain: 'airplanenurf.firebaseapp.com',
    storageBucket: 'airplanenurf.firebasestorage.app',
  );
}
