name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # You can specify the Flutter version you need

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'flutter format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      # Analyze project source
      - name: Analyze project source
        run: flutter analyze

      # Run tests
      # - name: Run tests
      #   run: flutter test
